# Generated by Django 4.1 on 2023-12-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_student_options_student_sex_alter_student_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, verbose_name="用户名")),
                ("token", models.CharField(max_length=20, verbose_name="token")),
            ],
        ),
    ]
