# Generated by Django 4.1 on 2023-12-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, verbose_name="用户名")),
                ("token", models.CharField(max_length=50, verbose_name="token")),
                ("dataset_name", models.CharField(max_length=50, verbose_name="数据集名称")),
                ("dataset_created_time", models.DateTimeField(verbose_name="数据集创建时间")),
                ("dataset_updated_time", models.DateTimeField(verbose_name="数据集更新时间")),
                ("img_name", models.CharField(max_length=50, verbose_name="图片名称")),
                ("img_created_time", models.DateTimeField(verbose_name="图片创建时间")),
                ("img_class", models.CharField(max_length=50, verbose_name="图片类别")),
                ("img_show", models.ImageField(upload_to="img", verbose_name="图片展示")),
            ],
        ),
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "账户", "verbose_name_plural": "账户"},
        ),
        migrations.AlterField(
            model_name="account",
            name="token",
            field=models.CharField(max_length=50, verbose_name="token"),
        ),
    ]
