# Generated by Django 4.1 on 2023-12-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_data_alter_account_options_alter_account_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="account",
        ),
        migrations.DeleteModel(
            name="student",
        ),
        migrations.AlterField(
            model_name="data",
            name="img_show",
            field=models.ImageField(
                upload_to="static/data/pictures", verbose_name="图片展示"
            ),
        ),
    ]
